### ISSUE TITLE
How to disable the auto update check

### ISSUE THREAD

**Issue by zhump678** [cage1016/alfred-opencc#4]
Thanks for this awesome workflow! 

But how can I disable the auto update check? Since the auto update check always occupys the first enty, and I am not planning to upgrade Alfred 5 yet.
![image](https://user-images.githubusercontent.com/33290353/204447397-974d14e9-efc8-45be-9c76-1137ba2a3705.png)
![image](https://user-images.githubusercontent.com/33290353/204447661-b3aa6978-d68a-4dd8-af6a-fe36fa7611e3.png)

Thanks

**Comment by cage1016** [comment]
Please manual download [Release v0.3.0 · cage1016/alfred-opencc](https://github.com/cage1016/alfred-opencc/releases/tag/v0.3.0). 

set `CHECK_FOR_UPDATE` as 0 to disable auto check for update

**Comment by zhump678** [comment]
> 

Great thx!!!
